// riskprof-react/src/components/CreateOrEditRating.js
import React from 'react';
import { Button } from 'react-bootstrap';
import Modal from "react-bootstrap/Modal";


class CreateOrEditRating extends React.Component {

    constructor(props) {
        super(props);

        this.state = {
            isOpen: false,
            isNewRating: true,
            rating: null
        }
    }

    show = (rating = null, parent = null) => {
        var isNewRating = rating === null;
        rating = rating || {
            id: -1,
            parent,
            parentId: parent?.id,
            title: "",
            key: ""
        };

        this.setState({
            isOpen: true,
            isNewRating,
            rating,
            children: []
        });
    }

    hide = () => {
        this.setState({ isOpen: false });
    }

    onHide = () => {
        this.hide();
    }

    handleInputChange = (event) => {
        const target = event.target;
        var rating = this.state.rating;
        rating[target.name] = target.value;
        this.setState({ rating });
    }

    save = () => {
        this.props.onSave(this.state.rating);
        this.hide();
    }

    render() {
        return (
            <Modal show={this.state.isOpen} onHide={this.onHide}>
                <Modal.Header>
                    <Modal.Title>{this.state.isNewRating ? 'Новый рейинг' : 'Редактировать рейтинг'}</Modal.Title>
                </Modal.Header>
                <Modal.Body>
                    <div className="form-group">
                        <label htmlFor="title">Title</label>
                        <input onChange={this.handleInputChange} 
                               value={this.state.rating?.title} 
                               type="text" className="form-control" name="title" id="title"/>
                        <label htmlFor="key">Key</label>
                        <input onChange={this.handleInputChange} 
                               value={this.state.rating?.key}
                               type="text" className="form-control" name="key" id="key"/>
                    </div>
                </Modal.Body>
                <Modal.Footer>
                    <Button onClick={this.hide}>Cancel</Button>
                    <Button onClick={this.save}>Save</Button>
                </Modal.Footer>
            </Modal>
        )
    }

}

export default CreateOrEditRating;

// riskprof-ng/src/app/create-or-edit-rating/create-or-edit-rating.component.ts
import { Component, OnInit, Output, TemplateRef, ViewChild, EventEmitter } from '@angular/core';
import { NgbModal, NgbModalRef } from '@ng-bootstrap/ng-bootstrap';
import { RatingDto } from 'src/common/models/RatingDto.class';
import { ApiService } from 'src/services/api.service';

@Component({
    selector: 'create-or-edit-rating',
    templateUrl: './create-or-edit-rating.component.html',
    styleUrls: ['./create-or-edit-rating.component.less']
})
export class CreateOrEditRatingComponent implements OnInit {

    rating: RatingDto;
    
    @Output() created: EventEmitter<RatingDto> = new EventEmitter<RatingDto>();
    @ViewChild("modalTemplate", { read: TemplateRef }) template: TemplateRef<any>;
    modalRef: NgbModalRef;
    isNewRating: boolean = false;

    constructor(private modalService: NgbModal, private _apiService: ApiService) { }

    ngOnInit(): void {
    }
    
    show(rating: RatingDto = null, parent: RatingDto = null) {
        if (!rating) {
            this.rating = new RatingDto();
            this.rating.parent = parent;
            this.rating.parentId = parent?.id;
            this.isNewRating = true;
        } else {
            this.rating = rating;
            this.isNewRating = false;
        }
        this.modalRef = this.modalService.open(this.template);
    }

    save () {
        if (this.isNewRating)
            this._apiService.create(this.rating).subscribe(createdRating => {
                if (createdRating.id) {
                    this.created.emit(createdRating);
                    this.close();
                } else {
                    alert("Произошла ошибка при создании рейтинга!");
                }
            });
        else 
            this._apiService.update(this.rating).subscribe(updatedRating => {
                this.close();
            });
    }

    close () {
        this.modalRef.close();
    }

}

<ng-template #modalTemplate>
    <div class="modal-header">
        <h4 class="modal-title">
            {{ (isNewRating) ? 'Новый рейинг' : 'Изменить рейтинг' }}
        </h4>
        <button type="button" class="close" aria-label="Close" (click)="close()">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <form>
            <div class="form-group">
                <label for="title">Title</label>
                <input [(ngModel)]="rating.title" type="text" class="form-control" name="title" id="title">
                <label for="key">Key</label>
                <input [(ngModel)]="rating.key" type="text" class="form-control" name="key" id="key">
            </div>
        </form>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-outline-dark" (click)="save()">Save</button>
    </div>
</ng-template>
