// riskprof-react/src/components/CreateOrEditRating.js
import React from 'react';
import { Button } from 'react-bootstrap';
import Modal from "react-bootstrap/Modal";


class CreateOrEditRating extends React.Component {

    constructor(props) {
        super(props);

        this.state = {
            isOpen: false,
            isNewRating: true,
            rating: null
        }
    }

    show = (rating = null, parent = null) => {
        var isNewRating = rating === null;
        rating = rating || {
            id: -1,
            parent,
            parentId: parent?.id,
            title: "",
            key: ""
        };

        this.setState({
            isOpen: true,
            isNewRating,
            rating,
            children: []
        });
    }

    hide = () => {
        this.setState({ isOpen: false });
    }

    onHide = () => {
        this.hide();
    }

    handleInputChange = (event) => {
        const target = event.target;
        var rating = this.state.rating;
        rating[target.name] = target.value;
        this.setState({ rating });
    }

    save = () => {
        this.props.onSave(this.state.rating);
        this.hide();
    }

    render() {
        return (
            <Modal show={this.state.isOpen} onHide={this.onHide}>
                <Modal.Header>
                    <Modal.Title>{this.state.isNewRating ? 'Новый рейинг' : 'Редактировать рейтинг'}</Modal.Title>
                </Modal.Header>
                <Modal.Body>
                    <div className="form-group">
                        <label htmlFor="title">Title</label>
                        <input onChange={this.handleInputChange} 
                               value={this.state.rating?.title} 
                               type="text" className="form-control" name="title" id="title"/>
                        <label htmlFor="key">Key</label>
                        <input onChange={this.handleInputChange} 
                               value={this.state.rating?.key}
                               type="text" className="form-control" name="key" id="key"/>
                    </div>
                </Modal.Body>
                <Modal.Footer>
                    <Button onClick={this.hide}>Cancel</Button>
                    <Button onClick={this.save}>Save</Button>
                </Modal.Footer>
            </Modal>
        )
    }

}

export default CreateOrEditRating;

// riskprof-vue3/src/components/CreateOrEditRating.vue
<template>
  <div class="modal fade show">
    <div @click="cancel()" class="backdrop"></div>
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">{{ title }}</h5>
          <button @click="cancel()" class="close">
            <span>&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div className="form-group">
            <label htmlFor="title">Title</label>
            <input
              v-model="rating.Title"
              id="title" type="text" className="form-control"
            />
            <label htmlFor="key">Key</label>
            <input
              v-model="rating.Key"
              id="key" type="text" className="form-control"
            />
          </div>
        </div>
        <div class="modal-footer">
          <button @click="save()" type="button" class="btn btn-primary">
            Save changes
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "CreateOrEditRating",
  methods: {
    save: function () {
      this.$emit("saved", this.rating);
    },
    cancel: function () {
      this.$emit("canceled");
    },
  },
  data() {
    return {
      rating: {},
      opened: false,
    };
  },
  props: {
    model: Object,
  },
  computed: {
      title() {
          return (this.rating.Id === null) ? "Новый рейтинг" : "Редактировать рейтинг";
      }
  },
  mounted() {
    if (this.model === null)
      this.rating = {
        Id: null,
        Key: null,
        ParentId: null,
        Title: "",
        parent: null,
      };
    else this.rating = this.model;
  },
};
</script>

<style lang="scss">
.modal.show {
  display: block;
  .modal-dialog {
    z-index: 2;
  }
  .backdrop {
    position: fixed;
    z-index: 1;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: rgba(0, 0, 0, 0.4);
  }
}
</style>
