// riskprof-svelte/src/Ratings.svelte

<script>
    import CreateOrEditRating from './CreateOrEditRating.svelte';
    import { ratingStore } from './store';
    import { Button } from 'sveltestrap';
    import { onMount } from 'svelte';

    var ratings = [];
    var status = "Root";
    var activeRating = null;
    var modalOpened = false;
    var ratingToEdit = null;

    onMount (() => {
        ratingStore.subscribe(value => {
            ratings = value;
        });
        ratingStore.getRatings(null);
    })

    function goUp() {
        if (activeRating !== null) {
            activeRating = activeRating.parent;
            status = activeRating?.title || "Root";
            ratingStore.getRatings(activeRating);
        }
    }

    function loadRating(rating) {
        activeRating = rating;
        status = rating.title;
        ratingStore.getRatings(rating);
    }

    function editRating(rating, e) {
        e.stopPropagation();
        modalOpened = true;
        ratingToEdit = rating;
    }

    function deleteRating(rating, e) {
        e.stopPropagation();
        if (confirm(`Удалить рейтинг ${rating.title}?`))
            ratingStore.deleteRating(rating);
    }

    function createRating() {
        modalOpened = true;
        ratingToEdit = {
            id: null, 
            key: "",
            title: "",
            parent: activeRating,
            parentId: activeRating?.id
        }
    }

    function saveRating(rating) {
        console.log(rating);
        ratingToEdit = rating;
        if (rating.id)
            ratingStore.updateRating(rating);
        else 
            ratingStore.createRating(rating);
    }

</script>

<div className="col-12 mt-4">
    <h2>{ status }</h2>
</div>
<div className="col-12 mt-1">
    <Button on:click={ goUp } color="primary">Вверх</Button>
    <Button on:click={ createRating } color="primary">Создать новый</Button>
</div>

<ul class="list-group">
    {#each ratings as rating}
        <li class="list-group-item list-group-item-action"
            on:click={() => loadRating(rating)}>
            { rating.title }
            <Button color="danger" on:click={(e) => deleteRating(rating, e)}>Удалить</Button>
            <Button color="light" on:click={(e) => editRating(rating, e)}>Изменить</Button>
        </li>
    {/each}
</ul>


<CreateOrEditRating open={modalOpened} rating={ratingToEdit} saved={saveRating}/>

// riskprof-vue3/src/components/Ratings.vue
<template>
    <div class="row">
        <div class="col-12 mt-4">
            <h3>{{ status }}</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-12 mt-2 mb-2">
            <button class="btn btn-outline-primary"
                    @click="goUp()">Вверх</button>
            <button class="btn btn-outline-primary ml-2"
                    @click="createRating()">Создать новый</button>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <ul class="list-group">
                <a class="list-group-item list-group-item-action"
                   v-for="rating in ratings"
                   @click="loadRating(rating)"
                   :key="rating.Id">
                   {{ rating.Title }}
                    <button className="btn btn-outline-danger btn-sm ml-1 float-right"
                        @click.stop="deleteRating(rating)">Удалить</button>
                    <button className="btn btn-secondary btn-sm float-right"
                        @click.stop="updateRating(rating)">Изменить</button>
                </a>
            </ul>
        </div>
    </div>
    <CreateOrEditRating 
        v-if="modalOpened" 
        :model="ratingToEdit" 
        @saved="onModalSaved"
        @canceled="onModalCancel"/>
</template>

<script>
import CreateOrEditRating from './CreateOrEditRating';

export default {
    methods: {
        goUp: function() {
            if (this.activeRating !== null) {
                this.activeRating = this.activeRating.parent;

                if (this.activeRating === null)
                    this.$store.dispatch("getRootRatings");
                else
                    this.$store.dispatch("getRatingChildren", this.activeRating);
            }
        },

        loadRating: function(rating) {
            this.activeRating = rating;
            this.$store.dispatch("getRatingChildren", this.activeRating);
        },
        
        createRating: function() {
            this.modalOpened = true;
            this.ratingToEdit = null;
        },

        updateRating: function(rating) {
            this.modalOpened = true;
            this.ratingToEdit = rating;
        },

        deleteRating: function(rating) {
            if (window.confirm("Удалить рейтинг " + rating.Title + "?"))
                this.$store.dispatch("deleteRating", rating.Id);
        },

        onModalSaved: function (savedRating) {
            if (savedRating.Id === null) {
                // CREATE
                savedRating.parent = this.activeRating;
                savedRating.ParentId = this.activeRating.Id;
                this.$store.dispatch("createRating", savedRating);
            } else {
                // UPDATE
                this.$store.dispatch("updateRating", savedRating);
            }

            this.modalOpened = false;
            this.ratingToEdit = null;
        },
        
        onModalCancel: function () {
            this.modalOpened = false;
            this.ratingToEdit = null;
        }
    },
    
    name: "Ratings",
    
    data() {
        return {
            activeRating: null,
            ratingToEdit: null,
            modalOpened: false
        };
    },
    
    computed: {
        status() {
            return this.activeRating?.Title || "Root";
        },
        ratings() {
            return this.$store.getters.ratings;
        },
    },
    
    created() {
        this.$store.dispatch("getRootRatings");
    },

    components: {
        CreateOrEditRating
    }
};
</script>
